# Generated by Django 2.0.9 on 2018-12-05 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnames_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'get_latest_by': 'created_date', 'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='name',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='updated_at',
            new_name='modified_date',
        ),
        migrations.AddField(
            model_name='name',
            name='is_deleted',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deleted'), (0, 'Active')], default=0, help_text='Is the record deleted'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(help_text='The name as written in the literature', max_length=100),
        ),
    ]
