# Generated by Django 2.0.9 on 2018-12-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0002_auto_20181205_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='name',
            old_name='modified_date',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(help_text='Enter a Name (e.g. Katian, Viru, etc.)', max_length=200),
        ),
    ]
