# Generated by Django 2.0.9 on 2018-12-20 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnames_app', '0015_auto_20181220_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deleted'), (0, 'Active')], default=0, help_text='Is the record deleted')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_structuredname', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.Location')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_structuredname', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.Name')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.Qualifier')),
            ],
            options={
                'ordering': ['name', 'qualifier', 'location'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='structuredname',
            unique_together={('name', 'qualifier', 'location')},
        ),
    ]
