# Generated by Django 2.0.9 on 2018-12-21 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnames_app', '0016_auto_20181220_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deleted'), (0, 'Active')], default=0, help_text='Is the record deleted')),
                ('belongs_to', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Belongs to')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_relation', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_relation', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('name_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameone_relation', to='rnames_app.Name')),
                ('name_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nametwo_relation', to='rnames_app.Name')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.Reference')),
            ],
            options={
                'ordering': ['reference', 'name_one', 'name_two'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('reference', 'name_one', 'name_two')},
        ),
    ]
