# Generated by Django 2.0.9 on 2018-12-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0018_auto_20181221_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['first_author', 'year', 'title']},
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='name',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='qualifiername',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='reference',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='relation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='stratigraphicqualifier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
        migrations.AddField(
            model_name='structuredname',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the record active'),
        ),
    ]
