# Generated by Django 2.0.9 on 2018-12-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0019_auto_20181223_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='name',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='qualifier',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='qualifiername',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stratigraphicqualifier',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='structuredname',
            name='is_deleted',
        ),
    ]
