# Generated by Django 3.0.3 on 2020-03-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0024_auto_20200305_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuredname',
            options={'ordering': ['name', 'qualifier', 'location', 'reference']},
        ),
        migrations.AddField(
            model_name='historicalstructuredname',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rnames_app.Reference'),
        ),
        migrations.AddField(
            model_name='historicalstructuredname',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Structured Name', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='structuredname',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rnames_app.Reference'),
        ),
        migrations.AddField(
            model_name='structuredname',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter remarks for the Structured Name', max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='structuredname',
            unique_together={('name', 'qualifier', 'location', 'reference')},
        ),
    ]
