# Generated by Django 3.0.3 on 2020-03-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0025_auto_20200309_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstructuredname',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Reference is not required unless you want to distinguish between two similar Structured Names', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rnames_app.Reference'),
        ),
        migrations.AlterField(
            model_name='structuredname',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='Reference is not required unless you want to distinguish between two similar Structured Names', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rnames_app.Reference'),
        ),
    ]
