# Generated by Django 3.0.3 on 2020-08-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0028_auto_20200526_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binning',
            name='binning_scheme',
            field=models.CharField(choices=[('x_robinb', 'Ordovician Time Slices (Bergström)'), ('x_robinw', 'Ordovician Time Slices (Webby)'), ('x_robins', 'Phanerozoic Stages (ICS Chart, 2020)'), ('x_robinp', 'Phanerozoic Epochs (ICS Chart, 2020)')], help_text='The Binning Scheme', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalbinning',
            name='binning_scheme',
            field=models.CharField(choices=[('x_robinb', 'Ordovician Time Slices (Bergström)'), ('x_robinw', 'Ordovician Time Slices (Webby)'), ('x_robins', 'Phanerozoic Stages (ICS Chart, 2020)'), ('x_robinp', 'Phanerozoic Epochs (ICS Chart, 2020)')], help_text='The Binning Scheme', max_length=200),
        ),
    ]
