# Generated by Django 2.0.9 on 2018-12-05 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0004_auto_20181205_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='updated_date',
            new_name='modified_on',
        ),
        migrations.AlterField(
            model_name='name',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='name',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='name_modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
