# Generated by Django 2.0.9 on 2018-12-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0012_stratigraphicqualifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Enter a Location (e.g. Sweden, Baltoscandia, New Mexico, China, North Atlantic, etc.)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(help_text='Enter a Name (e.g. Katian, Viru, etc.)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='qualifiername',
            name='name',
            field=models.CharField(help_text='Enter a Qualifier Name (e.g. Trilobite Sub Zone, Chemo zone, Formation, my, Regional stage etc.)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stratigraphicqualifier',
            name='name',
            field=models.CharField(help_text='Enter a a Stratigraphic Qualifier Name (e.g. Lithostratigraphy, Chemostratigraphy, Sequence stratigraphy, Asolute age, Chronostratigraphy, Biostratigraphy, etc.)', max_length=200, unique=True),
        ),
    ]
