# Generated by Django 2.0.9 on 2018-12-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnames_app', '0013_auto_20181208_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deleted'), (0, 'Active')], default=0, help_text='Is the record deleted')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, help_text='The level within the Qualifier hiearchy')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_qualifier', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_qualifier', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('qualifier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.QualifierName')),
            ],
            options={
                'ordering': ['stratigraphic_qualifier', 'level', 'qualifier_name'],
            },
        ),
        migrations.AlterField(
            model_name='stratigraphicqualifier',
            name='name',
            field=models.CharField(help_text='Enter a Stratigraphic Qualifier Name (e.g. Lithostratigraphy, Chemostratigraphy, Sequence stratigraphy, Asolute age, Chronostratigraphy, Biostratigraphy, etc.)', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='stratigraphic_qualifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnames_app.StratigraphicQualifier'),
        ),
    ]
