# Generated by Django 2.0.9 on 2019-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0022_auto_20181231_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreference',
            name='title',
            field=models.CharField(help_text='Enter the title of the reference', max_length=250),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(help_text='Enter the title of the reference', max_length=250),
        ),
    ]
