# Generated by Django 3.0.3 on 2020-03-05 14:19

from django.db import migrations, models
import rnames_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0023_auto_20190108_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=50, null=True, validators=[rnames_app.models.validate_doi]),
        ),
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, help_text='Enter the DOI number that begins with 10 followed by a period', max_length=50, null=True, validators=[rnames_app.models.validate_doi]),
        ),
    ]
