# Generated by Django 3.0.3 on 2020-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0027_binning_historicalbinning'),
    ]

    operations = [
        migrations.AddField(
            model_name='binning',
            name='rule',
            field=models.CharField(default='0', help_text='Enter the rule for the Binning.', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbinning',
            name='rule',
            field=models.CharField(default=0, help_text='Enter the rule for the Binning.', max_length=5),
            preserve_default=False,
        ),
    ]
