# Generated by Django 3.2.6 on 2021-10-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0030_historicaltimeslice_timeslice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslice',
            options={'ordering': ['scheme', 'order']},
        ),
    ]
