# Generated by Django 3.2.6 on 2021-10-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0031_alter_timeslice_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslice',
            unique_together=set(),
        ),
    ]
