# Generated by Django 3.2.6 on 2021-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnames_app', '0032_alter_timeslice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinningProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('text', models.CharField(default='', max_length=1000)),
                ('value_one', models.IntegerField(default=0)),
                ('value_two', models.IntegerField(default=0)),
            ],
        ),
    ]
