# Generated by Django 2.0.9 on 2019-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsourcereference',
            name='Citation',
            field=models.CharField(default='Enter the citation of the Source Reference', help_text='Enter the citation of the Source Reference', max_length=250),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='Citation',
            field=models.CharField(default='Enter the citation of the Source Reference', help_text='Enter the citation of the Source Reference', max_length=250),
        ),
    ]
