# Generated by Django 2.0.9 on 2019-01-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0002_auto_20190116_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcereference',
            options={'ordering': ['citation']},
        ),
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='Citation',
        ),
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='first_author',
        ),
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='link',
        ),
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='year',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='Citation',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='first_author',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='link',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='year',
        ),
        migrations.AddField(
            model_name='historicalsourcereference',
            name='citation',
            field=models.CharField(default='def', help_text='Enter the Citation of the Source Reference', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='citation',
            field=models.CharField(default='s', help_text='Enter the Citation of the Source Reference', max_length=250),
            preserve_default=False,
        ),
    ]
