# Generated by Django 2.0.9 on 2019-01-16 12:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0003_auto_20190116_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMasterReference',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('type', models.CharField(help_text='Enter the Type of the Master Reference', max_length=25)),
                ('doi', models.URLField(blank=True, help_text='Enter a valid DOI URL for the Master Reference', null=True)),
                ('first_author', models.CharField(blank=True, help_text='Enter the name of the first author of the Maste Reference', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('title', models.CharField(help_text='Enter the Title of the Master Reference', max_length=250)),
                ('container_title', models.CharField(help_text='Enter the Container Title of the Master Reference', max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)])),
                ('issue', models.CharField(help_text='Enter the Issue of the Master Reference', max_length=5)),
                ('citation', models.CharField(help_text='Enter the Citation of the Master Reference', max_length=400)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'verbose_name': 'historical master reference',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MasterReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('type', models.CharField(help_text='Enter the Type of the Master Reference', max_length=25)),
                ('doi', models.URLField(blank=True, help_text='Enter a valid DOI URL for the Master Reference', null=True)),
                ('first_author', models.CharField(blank=True, help_text='Enter the name of the first author of the Maste Reference', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('title', models.CharField(help_text='Enter the Title of the Master Reference', max_length=250)),
                ('container_title', models.CharField(help_text='Enter the Container Title of the Master Reference', max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000)])),
                ('issue', models.CharField(help_text='Enter the Issue of the Master Reference', max_length=5)),
                ('citation', models.CharField(help_text='Enter the Citation of the Master Reference', max_length=400)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_masterreference', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_masterreference', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'ordering': ['citation'],
            },
        ),
        migrations.AddField(
            model_name='historicalsourcereference',
            name='master_reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.MasterReference'),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='master_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.MasterReference'),
        ),
    ]
