# Generated by Django 2.0.9 on 2019-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0004_auto_20190116_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterreference',
            name='page',
            field=models.CharField(blank=True, help_text='Enter the Page(s) of the Master Reference', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalsourcereference',
            name='slug',
            field=models.SlugField(default='slug', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsourcereference',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created - Not verified'), (2, 'Verified - Accepted'), (3, 'Verified - Rejected')], default=1, help_text='Status to Master Reference'),
        ),
        migrations.AddField(
            model_name='masterreference',
            name='page',
            field=models.CharField(blank=True, help_text='Enter the Page(s) of the Master Reference', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='slug',
            field=models.SlugField(default='test', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created - Not verified'), (2, 'Verified - Accepted'), (3, 'Verified - Rejected')], default=1, help_text='Status to Master Reference'),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='issue',
            field=models.CharField(blank=True, help_text='Enter the Issue of the Master Reference', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmasterreference',
            name='type',
            field=models.CharField(blank=True, help_text='Enter the Type of the Master Reference', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='issue',
            field=models.CharField(blank=True, help_text='Enter the Issue of the Master Reference', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='masterreference',
            name='type',
            field=models.CharField(blank=True, help_text='Enter the Type of the Master Reference', max_length=25, null=True),
        ),
    ]
