# Generated by Django 2.0.9 on 2019-01-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0005_auto_20190116_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsourcereference',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sourcereference',
            name='slug',
        ),
    ]
