# Generated by Django 2.0.9 on 2019-01-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0011_auto_20190117_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrelation',
            name='entity',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mb.EntityClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalentityrelation',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.EntityClass'),
        ),
    ]
