# Generated by Django 2.0.9 on 2019-01-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0014_choicevalue_fooditem_historicalchoicevalue_historicalfooditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicevalue',
            options={'ordering': ['choice_set', 'caption']},
        ),
        migrations.AddField(
            model_name='fooditem',
            name='part',
            field=models.ForeignKey(limit_choices_to={'choice_set': 'FoodItemPart'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mb.ChoiceValue'),
        ),
        migrations.AddField(
            model_name='historicalfooditem',
            name='part',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'choice_set': 'FoodItemPart'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.ChoiceValue'),
        ),
        migrations.AlterUniqueTogether(
            name='choicevalue',
            unique_together={('choice_set', 'caption')},
        ),
    ]
