# Generated by Django 2.0.9 on 2019-01-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mb', '0015_auto_20190117_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby_dietset', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('location', models.ForeignKey(limit_choices_to=models.Q(('entity__name', 'Location'), ('entity__name', 'Location'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='location_dietset', to='mb.SourceEntity')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiedby_dietset', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb.SourceReference')),
                ('taxon', models.ForeignKey(limit_choices_to=models.Q(('entity__name', 'Species'), ('entity__name', 'Species'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='taxon_dietset', to='mb.SourceEntity')),
            ],
            options={
                'ordering': ['taxon___name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDietSet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('history_change_reason', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the record active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('entity__name', 'Location'), ('entity__name', 'Location'), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceEntity')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceReference')),
                ('taxon', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to=models.Q(('entity__name', 'Species'), ('entity__name', 'Species'), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mb.SourceEntity')),
            ],
            options={
                'verbose_name': 'historical diet set',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='dietset',
            unique_together={('reference', 'taxon', 'location')},
        ),
    ]
